name: customelement_signin_1
description: First version about customelement in dart & signin form
dependencies:
  polymer: '>=0.12.0-dev <0.13.0'
  core_elements: ">=0.0.6 <0.1.0"
  paper_elements: "any"
  intl: ">=0.11.2 <0.12.0"
transformers:
- polymer:
    entry_points: web/index.html
